[package]
name = "watt-demo-caller"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
wa-demo = { path = "../wa" }

[features]
feat_a = ["wa-demo/feat_a"]
feat_b = ["wa-demo/feat_b"]
